ImportError while loading conftest 'C:\Users\mjmil\Documents\recipe_app\tests\conftest.py'.
tests\conftest.py:11: in <module>
    from app.core.database.base import Base
app\core\__init__.py:7: in <module>
    from .models import (
app\core\models\__init__.py:3: in <module>
    from .recipe import Recipe
app\core\models\recipe.py:17: in <module>
    from .recipe_ingredient import RecipeIngredient
app\core\models\recipe_ingredient.py:16: in <module>
    from ..dtos.ingredient_dtos import IngredientDetailDTO
app\core\dtos\__init__.py:21: in <module>
    from .planner_dtos import (
app\core\dtos\planner_dtos.py:105: in <module>
    MealSelectionResponseDTO.model_rebuild()
.venv\Lib\site-packages\pydantic\main.py:654: in model_rebuild
    raise exc from e
E   pydantic.errors.PydanticUndefinedAnnotation: name 'Recipe' is not defined
E
E   For further information visit https://errors.pydantic.dev/2.11/u/undefined-annotation
Initializing Meal Planner v1.0.0
